apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: github-runner-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: github-runner
  minReplicas: 1  # Minimum number of replicas
  maxReplicas: 5  # Maximum number of replicas
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 50  # Adjust this as needed
